"""
Prompt
"""

from .prompt import (
    INTERVIEWER_SYSTEM_PROMPT,

    QUESTION_GENERATION_PROMPT,

    FOLLOW_UP_DECISION_PROMPT,

    QUESTION_ADJUSTMENT_PROMPT,

    INTERVIEW_END_DECISION_PROMPT,

    DEEP_THINKING_PROMPT_QUESTION_BUILD,
    DEEP_THINKING_PROMPT_ADJUST_QUESTION,
    DEEP_THINKING_PROMPT_DEEP_QUESTION,

    TOOL_CALLING_DECISION_PROMPT,
)

__all__ = [
    "INTERVIEWER_SYSTEM_PROMPT",
    "QUESTION_GENERATION_PROMPT",
    "FOLLOW_UP_DECISION_PROMPT",
    "QUESTION_ADJUSTMENT_PROMPT",
    "INTERVIEW_END_DECISION_PROMPT",
    "TOOL_CALLING_DECISION_PROMPT",
    "DEEP_THINKING_PROMPT_QUESTION_BUILD",
    "DEEP_THINKING_PROMPT_ADJUST_QUESTION",
    "DEEP_THINKING_PROMPT_DEEP_QUESTION",
]
